### ISSUE TITLE
项目设想：时间记录助手

### ISSUE THREAD

**Issue by sunoonlee** [sunoonlee/OMOOC2py#8]
#### 时间记录助手 - 简介
汇总分散在各处的时间记录，实现个性化的图表输出、量化评价等时间管理辅助

#### 潜在用户：
- 时间记录爱好者

#### 问题/背景：
- 日常时间记录可能分散在不同应用中，但缺少一个统一的平台来汇总，包括：
  + 用 pomotodo 之类的番茄工作法应用记录专注脑力劳动的时间
  + 在桌面端用 manictime 或 rescuetime 等记录电脑使用信息
  + 用 移动端的 gleeo time tracker 或 atimelogger 等应用随时随地记录一些时间开销
  + 运动信息可能记录在咕咚/garmin express 等应用中
  + 作息时间信息可能记录在 sleepbot 或其他类似应用中，等等
- 现有的时间记录应用，在图表输出、自我量化评价、时间管理PDCA等方面未必满足我们的个性化需求

#### 解决思路：
- 数据输入
  - 自动读入其他app的记录，转换为统一格式，汇总到本app的数据库中
  - 也提供应用内自行输入方式
- 数据输出
  - 提供灵活的记录显示/统计/查询方式
  - 提供高定制性的图表输出方式，参考 manictime
  - 分不同模块：产出、运动、作息 (and maybe 爱好、读书、不得不做的事），重点关注高质量时间
    - 产出模块：关注不同项目的番茄/时间投入情况
- 自我评价与改进
  - 可自行设定自我量化评价指数，如 生产力指数、生活丰富度指数等
  - 辅助用户改进时间管理：提供目标设定、结果评价等入口

#### 预期的技术难点：
- 各种 app 的数据提取
  + 兼容的 app 越多，工作量越大
- 丰富的图表输出功能的实现
- 用户数据的保密
- 或许技术不是难点，只是时间问题
- 更关键的是逻辑、交互的设计
  + 如何让需求从最简单到较复杂的不同用户群都能愉快使用

#### 关于发起人
- 坐标：成都
- 能保证每周 20 h以上的时间投入
- 时间观
  - 番茄工作法重度用户
    - 工具：pomotodo.com
  - 曾有数月详细记录时间开销
    - 工具：manictime, gleeo time tracker(android)
  - 折服于《奇特的一生》中的时间统计法，但倾向于更为灵活宽松的方式

**Comment by sunoonlee** [comment]
汇总个人生活中各种时间记录，生成图表， 提供自定义的量化自我评价

时间记录类型包括：番茄，作息，运动，爱好，读书，以及工作或生活中不得不做的事（如开会、通勤等）

重点记录高质量、有产出的时间

**Comment by sunoonlee** [comment]
数据来源：
pomotodo 及其他常见番茄应用
atimelogger、gleeo time tracker 或其他手机端时间记录应用
咕咚运动（及其他主流运动记录应用）
sleepbot 或其他作息记录应用manictime/rescuetime 记录
当然也支持手动输入

**Comment by sunoonlee** [comment]
图表功能：分不同模块，提供类似manictime那样强大且美观的图表

量化自我评价：生产力指数，健康指数，生活丰富指数等

**Comment by sunoonlee** [comment]
尚未来得及详细展开
今晚5点前会完善描述
欢迎有兴趣的同学一起来讨论

**Comment by aJiea** [comment]
大妈珠海c2t2推荐了一个时间管理的时间开销应用a time logger，供参考！

**Comment by sunoonlee** [comment]
下午发现一个现有应用，[Toggl](https://toggl.com/app)，很适于作为统一的时间管理平台

前期调研不足，本项目暂时搁置

**Comment by sunoonlee** [comment]
@aJiea aTimeLogger 只有移动端，不安逸呀
